version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Django
      - DJANGO_DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1

      # Database
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      # Mailing
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
      - EMAIL_HOST_USER=admin
      - EMAIL_HOST_PASSWORD=admin
      
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: always
      volumes:
        - ./data:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATA_FILE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1